### ISSUE TITLE
"Save to file" doesn't work?

### ISSUE THREAD

**Issue by Wizmann** [drichard/mindmaps#40] opened 2013-11-06 12:47 UTC
There is no response when I click the "Save to file" button.

Is that a bug?

**Comment by feluxe** [comment] 2017-02-09 02:17
I have the same issue.

**Comment by JonathanCedrim** [comment] 2017-02-28 15:28
for who is using, http://app.mindmapmaker.org/. 
Apparently and the new version

**Comment by Bbully** [comment] 2017-03-10 10:01
Solved! Enable _ShockWave Flash_ in your browser and save to file working.

**Comment by drichard** [comment] 2017-04-20 04:38
Duplicate of #60.

**Closed by drichard** 2017-04-20 04:38 UTC
